<?php
function sitemap_exclude_post_type( $value, $post_type ) {
  if ( $post_type == 'product' ) return true;
}
add_filter( 'wpseo_sitemap_exclude_post_type', 'sitemap_exclude_post_type', 10, 2 );

function gb_change_products_sitemap() {
  global $wpseo_sitemaps;
  if ( empty( $wpseo_sitemaps ) ) return;
  $wpseo_sitemaps->register_sitemap( 'products', 'create_product_sitemap' );
}
add_action( 'init', 'gb_change_products_sitemap', 99 );

function create_product_sitemap() {

  global $wpseo_sitemaps;

  $products_query = new WP_Term_Query([
    'taxonomy' => 'product_cat',
    'hide_empty' => false,
  ]);
  if ( empty( $products_query->terms ) ) return;
  $sitemap = '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';
  foreach ( $products_query->terms as $term ) {
    if ( get_field( 'hide_on_archive', 'term_' . $term->term_id ) ) continue;
    $url = get_term_link( $term );
    $sitemap .= '
      <url>
        <loc>' . $url . '</loc>
        <lastmod></lastmod>
        <changefreq>daily</changefreq>
        <priority>1.0</priority>
      </url>';
  }
  $sitemap .= '</urlset>';
  $wpseo_sitemaps->set_sitemap( $sitemap );
}

function gb_enable_custom_sitemap() {
   global $wpseo_sitemaps;
   if ( isset( $wpseo_sitemaps ) && ! empty ( $wpseo_sitemaps ) ) {
      $wpseo_sitemaps->register_sitemap( 'external', 'create_external_sitemap' );
   }
}
add_action( 'init', 'gb_enable_custom_sitemap' );

function gb_create_external_sitemap() {
   global $wpseo_sitemaps;

   $sitemap = '
   <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/190-cm/width/80-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/artikelen/melkglas-douchedeur/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/185-cm/dooropener/greep/width/90-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/douchedeur-sophia-75-cm-x-170-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/artikelen/vouw-douchedeur-op-maat/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/douchedeur-sophia-80-cm-x-165-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/150-cm/width/85-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/douchedeur-isabella-55-cm-x-150-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/dooropener/knop/height/155-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/160-cm/dooropener/knop/width/90-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://glasbestellen.nl/shop/douchedeur-sophia-55-cm-x-155-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/190-cm/width/90-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/185-cm/dooropener/knop/width/60-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/douchedeur-isabella-90-cm-x-165-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/85-cm/height/175-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/70-cm/dooropener/greep/height/165-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://glasbestellen.nl/shop/douchedeur-sophia-65-cm-x-170-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/85-cm/height/180-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/65-cm/dooropener/knop/height/180-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/leads/alexander-rengelink-fonville/attachment/douchedeur-14/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/60-cm/dooropener/knop/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/80-cm/height/200-cm/dooropener/knop/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/155-cm/dooropener/knop/width/70-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://glasbestellen.nl/shop/douchedeur-sophia-50-cm-x-165-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/artikelen/gekleurde-folie-op-douchedeur/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/artikelen/douchedeur-op-maat-oosterhout-gd/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/artikelen/douchedeur-strip-3-mm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/artikelen/glazen-douchedeur-60x200/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/artikelen/passtuk-douchedeur/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/douchedeur-sophia-50-cm-x-190-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/douchedeur-isabella-55-cm-x-170-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/douchedeur-emma-85-cm-x-200-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/75-cm/height/195-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/190-cm/width/50-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/85-cm/height/190-cm/dooropener/knop/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/artikelen/sphinx-douchedeur-onderdelen/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/200-cm/dooropener/knop/width/75-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/190-cm/page/2/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/douchedeur-olivia-70-cm-x-150-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/artikelen/huppe-douchedeur-demonteren/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/artikelen/megius-douchedeur-wieltjes/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/douchedeur-emma-65-cm-x-150-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/artikelen/inklapbare-douchedeur/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/70-cm/height/190-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/douchedeur-isabella-80-cm-x-180-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/55-cm/height/160-cm/dooropener/greep/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/dooropener/knop/height/175-cm/page/2/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/200-cm/dooropener/greep/width/90-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/55-cm/height/195-cm/dooropener/greep/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://glasbestellen.nl/measure-fitting/video-douchedeur/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/90-cm/dooropener/greep/height/175-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/85-cm/dooropener/knop/height/175-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/200-cm/width/75-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/artikelen/douchedeur-plexiglas/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/155-cm/width/80-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/page/16/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/werk//douchecabine-met-douchedeur-en-glazen-zijpaneel/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/dooropener/greep/width/60-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/artikelen/spatstrip-douchedeur/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/artikelen/glazen-douchedeur-beslag/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/75-cm/dooropener/knop/height/175-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/50-cm/height/165-cm/dooropener/knop/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/180-cm/dooropener/greep/width/85-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/195-cm/dooropener/knop/width/55-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/douchedeur-sophia-65-cm-x-200-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/65-cm/height/180-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/65-cm/height/150-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/90-cm/dooropener/greep/page/2/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/170-cm/dooropener/greep/width/75-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/50-cm/height/180-cm/dooropener/greep/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/65-cm/dooropener/greep/height/155-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/70-cm/height/200-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/195-cm/dooropener/greep/width/50-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/195-cm/dooropener/greep/width/85-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/155-cm/page/3/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://glasbestellen.nl/shop/shop-category/douchedeur/width/85-cm/dooropener/knop/height/165-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/artikelen/infinity-douchedeur-2/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/60-cm/dooropener/greep/height/160-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://glasbestellen.nl/shop/douchedeur-olivia-50-cm-x-160-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/douchedeur-sophia-70-cm-x-170-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://glasbestellen.nl/shop/douchedeur-emma-90-cm-x-165-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/artikelen/douchedeur-onderdelen-geleiders/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/dooropener/greep/height/190-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/70-cm/height/170-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/artikelen/nieuwe-bruynzeel-aqualine-driedelige-douchedeur/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/douchedeur-sophia-90-cm-x-175-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/65-cm/height/155-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/85-cm/dooropener/knop/height/165-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/185-cm/width/80-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/80-cm/dooropener/knop/height/180-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/70-cm/height/155-cm/dooropener/greep/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/dooropener/greep/height/200-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/50-cm/dooropener/greep/height/160-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/160-cm/dooropener/greep/width/55-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://glasbestellen.nl/werk/douchecabine/douchecabine-met-douchedeur-en-glazen-zijpaneel/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/artikelen/deelbare-douchedeur/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/width/80-cm/dooropener/greep/height/185-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/shop-category/douchedeur/height/195-cm/dooropener/knop/width/80-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
     <url>
       <loc>https://www.glasbestellen.nl/shop/douchedeur-sophia-60-cm-x-170-cm/</loc>
       <lastmod>2019-09-30</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0</priority>
     </url>
   </urlset>
   ';

   $wpseo_sitemaps->set_sitemap( $sitemap );
}

function gb_add_sitemap_custom_items( $sitemap_custom_items ) {
   $sitemap_custom_items .= '
      <sitemap>
         <loc>' . site_url( 'external-sitemap.xml' ) . '</loc>
         <lastmod>2019-09-30</lastmod>
      </sitemap>
      <sitemap>
        <loc>' . site_url( 'products-sitemap.xml' ) . '</loc>
        <lastmod></lastmod>
    </sitemap>

   ';
   return $sitemap_custom_items;
}
add_filter( 'wpseo_sitemap_index', 'gb_add_sitemap_custom_items' );
